- name: Ensure docker is running
  service:
    name: docker
    state: started
  become: true
  when:
    - ansible_os_family == 'Debian'

- name: "Add {{ lookup('env', 'USER') }} to docker group"
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: true
  when:
    - ansible_os_family == 'Debian'
