- name: Install powerline fonts via apt
  apt:
    name: tmux
  become: true
  when:
    - ansible_os_family == 'Debian'

- name: Check if .tmux.conf exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
  register: tmux_conf
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Create .tmux.conf
  file:
    path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: touch
  when:
    - not tmux_conf.stat.exists
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Get tmux-themepack
  git:
    repo: "https://github.com/jimeh/tmux-themepack.git"
    dest: "{{ lookup('env', 'HOME') }}/.tmux-themepack"
    version: 1b1b8098419daacb92ca401ad6ee0ca6894a40ca
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Configure .tmux.conf
  blockinfile:
    marker: "## TMUX CONFIGS {mark}"
    block: |
        # Powerline
        source-file "${HOME}/.tmux-themepack/powerline/double/blue.tmuxtheme"
        set -g @plugin 'jimeh/tmux-themepack'
        set -g @themepack 'powerline/double/blue'

        # mouse support
        set-window-option -g mode-keys vi
        set -g mouse on

        # history
        set -g history-limit 10000

        # clipboard
        # set-option -g default-command "reattach-to-user-namespace -l bash"

        # bind C-y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
        # bind C-p run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
    path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Configure .bash_profile
  blockinfile:
    marker: "## TMUX CONFIGS {mark}"
    block: |
        attach-tmuxsession(){
            if command -v tmux > /dev/null; then
                if [[ "$TERM" == "screen" ]]; then
                    return
                elif tmux ls | grep -v attached; then
                    LAST_UNATTACHED="$(tmux ls | grep -v attached | awk -F ':' 'END {print $1}')"
                    tmux attach -t "$LAST_UNATTACHED"
                else
                    exec tmux
                fi
            fi
        }

        attach-tmuxsession
    path: "{{ lookup('env', 'HOME') }}/.bash_profile"
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

