 - name: Clone all the things
   git:
     repo: "{{ item }}"
     dest: "{{ lookup('env', 'HOME') }}/Git/JLH993/{{ item.split('/')[-1].split('.')[0] }}"
   loop:
     - https://github.com/JLH993/python-reference.git
     - https://github.com/JLH993/linux-template-deploy.git
     - https://github.com/JLH993/security-scripts.git
     - https://github.com/JLH993/net-speed-test.git
     - https://github.com/JLH993/sherlock.git
     - https://github.com/JLH993/vapi.git
     - https://github.com/JLH993/kvm-backups.git
     - https://github.com/JLH993/lab-automation.git
   when:
     - ansible_os_family == 'Debian'
