- name: Get Terminal Profile
  shell: |
    set -o pipefail

    gsettings get org.gnome.Terminal.ProfilesList default | \
    {% raw %}
        grep -Pow '\w{8}(-\w{4}){3}-\w{12}'
    {% endraw %}
  args:
    executable: /bin/bash
  register: terminal
  changed_when: False
  when:
    - ansible_os_family == 'Debian'

- name: Create ansible terminal settings driectory
  file:
    path: "{{ lookup('env', 'HOME') }}/.ansible/terminal/"
    state: directory
    mode: 0755
  register: config_dir
  when:
    - ansible_os_family == 'Debian'

- name: Add Terminal Profile
  template:
    src: terminal-profile.dconf.j2
    dest: "{{ config_dir.path }}/terminal-profile.dconf"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
  register: terminal_profile
  when:
    - ansible_os_family == 'Debian'

- name: Import profile
  shell: "dconf reset -f /org/gnome/terminal/ && dconf load /org/gnome/terminal/ < {{ config_dir.path }}/terminal-profile.dconf"
  when:
    - ansible_os_family == 'Debian'
    - terminal.stdout != profile_guid or
      terminal_profile.changed
