- name: Check if .bash_profile exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.bash_profile"
  register: bash_profile
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Create .bash_profile
  file:
    path: "{{ lookup('env', 'HOME') }}/.bash_profile"
    state: touch
  when:
    - not bash_profile.stat.exists
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Configure .bash_profile
  blockinfile:
    marker: "## GENERIC SHELL CONFIGS {mark}"
    block: |
        {% raw %}
        # source .bashrc
        if [[ -f /etc/bashrc ]]; then
            source /etc/bashrc
        fi

        PATH="$PATH:$HOME/Scripts/.bin:$HOME/.bin"
        export CLICOLOR=1
        export LSCOLORS=GxFxCxDxBxegedabagaced

        # Shell Histroy:
        HISTTIMEFORMAT="%d/%m/%y %T -"
        HISTSIZE=10000

        # Functions
        Generate-Alias(){
            ALIAS="$1"
            FILE="$2"

            if [[ -f "$FILE" ]]; then
                # shellcheck disable=SC2139
                alias "${ALIAS}='$FILE'"
            fi
        }

        print(){
            var="$1";
            size="${#var}";
            printf -v sep "%${size}s" "-";
            printf "\n%s\n%s\n" "$var" "${sep// /-}";
        };

        ipinfo(){
            IP="$1"

            if [[ "$IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
                curl -Ls "ipinfo.io/$IP" | jq --indent 4
            else
                printf "%s does not appear to be a valid IP.\n" "$IP"
                return 1;
            fi;
        }

        Validate-CloudFormation(){
            DIR="$1"

            if [[ -z "$DIR" ]]; then
                DIR='.'
            fi

            while read -r FILE; do
                print "$FILE";

                cfn-lint "$FILE" &&
                    echo "No issues found.";
            done < <(
                find "$DIR" \
                    -name "*.yml" \
                    -not -path "*bamboo*" \
                    -not -path "*gitlab*"
            )
        }

        Check-AWSCreds(){
            while read -r PROFILE; do
                printf "%-20s - " "$PROFILE";
                aws s3 ls --profile "$PROFILE" &> /dev/null &&
                    printf "\e[38;5;2mworking\e[0m\n" ||
                        printf "\e[38;5;1mbroken\e[0m\n"
            done < <(
                grep '\[' ~/.aws/credentials | \
                    grep -Pow '[a-zA-Z\-]+'
            )
        }
        {% endraw %}
    dest: "{{ lookup('env', 'HOME') }}/.bash_profile"
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'
