- name: Create .gitconfig
  template:
    src: ../templates/.gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
  when:
    - ansible_os_family == 'Debian'
