- name: Install HomeBrew on MacOS devices
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  when: 
    - ansible_os_family == 'Darwin'

- name: Install HomeBrew\'d Applications
  homebrew:
    name: "{{ item }}"
  loop:
    - tree
    - wget
    - openssl
    - terraform
