- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - tree
    - curl
    - wget
    - docker.io
    - htop
    - nmap
    - jq
    - vim
    - python3-pip
  become: true
  when:
    - ansible_os_family == 'Debian'

