- name: Download spf13 setupscript
  get_url:
    url: https://j.mp/spf13-vim3
    dest: /tmp/spf13-setup.sh
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'

- name: Configure spf13
  script: /tmp/spf13-setup.sh
  args:
    executable: /bin/bash
    creates: "{{ lookup('env','HOME') }}/.spf13-vim-3"
  when:
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'Darwin'
